version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./game-server
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"

